# Generated by Django 5.0.1 on 2024-02-15 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Patient',
        ),
    ]
