# Generated by Django 5.0.1 on 2024-02-15 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('student', '0002_delete_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studentname', models.CharField(max_length=56)),
                ('studentage', models.CharField(max_length=5)),
                ('studentmobile', models.CharField(max_length=12)),
                ('studentcity', models.CharField(max_length=30)),
            ],
        ),
    ]
