# Generated by Django 5.0.1 on 2024-02-15 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='studentage',
            new_name='age',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='studentcity',
            new_name='city',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='studentmobile',
            new_name='mobile',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='studentname',
            new_name='name',
        ),
    ]
