# Generated by Django 5.0.1 on 2024-02-15 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('student', '0005_delete_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=56)),
                ('age', models.CharField(max_length=5)),
                ('mobile', models.CharField(max_length=12)),
                ('address', models.CharField(max_length=200)),
            ],
        ),
    ]
